# Use the official Golang image as a builder
FROM golang:alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy the source code to the working directory
COPY . .

# Build the Go application
RUN go build -o server ./golang/server.go

# Use a minimal Docker image to run the Go application
FROM alpine:latest

# Set the working directory inside the container
WORKDIR /root/

# Copy the built application from the builder image
COPY --from=builder /app/server .

# Copy the necessary files
COPY ./golang/file-dev.txt .
COPY ./golang/file-prod.txt .

# Accept an argument during build
ARG ENV=DEV

# Set the default environment
ENV ENV=$ENV

# Expose the port the server will run on
EXPOSE 8080

# Command to run the application
CMD ["./server"]
